#!/bin/bash 

exec 0</dev/null 1>&2

{ 
	find -L ../libr.d -type f -print0 | sort -z | xargs -0r cat | sed -r ':x; s/\(([A-Za-z](_?[A-Za-z0-9])*(\.[A-Za-z](_?[A-Za-z0-9])*)*)\.([A-Za-z](_?[A-Za-z0-9])*)\)/(get (\1) \5)/g; tx; s/#.*//; ' 
	cat "$1"
} | ../treep 

